Document: createap
Title: Debian createap Manual
Author: <insert document author here>
Abstract: This manual describes what createap is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/createap/createap.sgml.gz

Format: postscript
Files: /usr/share/doc/createap/createap.ps.gz

Format: text
Files: /usr/share/doc/createap/createap.text.gz

Format: HTML
Index: /usr/share/doc/createap/html/index.html
Files: /usr/share/doc/createap/html/*.html
